###############################################################################
# THE HOME ASSISTANT CONFIGURATION FILE - MOTHER OF ALL CONFIG FILES
# @Author   :   Mahasri Kalavala
###############################################################################
homeassistant:
  name: Home 
  temperature_unit: F
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  
  unit_system: imperial
  time_zone: !secret time_zone
  customize_glob: !include customize_glob.yaml  
  packages: !include_dir_named packages

updater:
discovery:
sun:
config:
logbook:
history:
python_script:

recorder:
  db_url: !secret my_sql_url

http:
  api_password: !secret api_password

mqtt:
  broker: !secret pi_hole_mqtt_server
  port: !secret pi_hole_mqtt_port
  username: !secret pi_hole_mqtt_username
  password: !secret pi_hole_mqtt_password
  keepalive: 60
  client_id: pi_ha

binary_sensor:
  - platform: workday
    country: US

emulated_hue:
  expose_by_default: false
  host_ip: !secret ha_ip_address
  listen_port: 8300
  # exposed_domains:
  #   - light

logger: !include logging.yaml
group: !include_dir_merge_named groups

ios:
  push:
    categories:
      - name: Single Car Garage Door
        identifier: '1CAR_GARAGE'
        actions:
          - identifier: '1CAR_GARAGE_CLOSE'
            title: 'Close Garage Door'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
      - name: Two Car Garage Door
        identifier: '2CAR_GARAGE'
        actions:
          - identifier: '2CAR_GARAGE_CLOSE'
            title: 'Close Garage Door'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
      - name: Trash Recycle
        identifier: 'TRASH_RECYCLE'
        actions:
          - identifier: 'TRASH_LEFT'
            title: 'Done'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
          - identifier: 'TRASH_REMIND_LATER'
            title: 'Remind Later'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

frontend:
  themes:
    princess_pink:
      dark-primary-color: "#ff084a"
      primary-color: "#fc3468"
      light-primary-color: "#ffc2cd"
      paper-toggle-button-checked-ink-color: "#ff6289"
      paper-toggle-button-checked-button-color: "#ff084a"
      paper-toggle-button-checked-bar-color: "#ffc2cd"
      paper-slider-knob-color: "#ff084a"
      paper-slider-knob-start-color: "#ff084a"
      paper-slider-pin-color: "#ff084a"
      paper-slider-active-color: "#ff084a"
      paper-slider-secondary-color: "#ff93ac"
    beach:
      dark-primary-color: "#88d8b0"
      primary-color: "#ff6f69"
      light-primary-color: "#ffcc5c"
      paper-toggle-button-checked-ink-color: "#ff6f69"
      paper-toggle-button-checked-button-color: "#88d8b0"
      paper-toggle-button-checked-bar-color: "#ffcc5c"
      paper-slider-knob-color: "#88d8b0"
      paper-slider-knob-start-color: "#88d8b0"
      paper-slider-pin-color: "#88d8b0"
      paper-slider-active-color: "#88d8b0"
      paper-slider-secondary-color: "#ffeead"      
    greens:
      dark-primary-color: "#009688"
      primary-color: "#009688"
      light-primary-color: "#009688"
      paper-toggle-button-checked-ink-color: "#009688"
      paper-toggle-button-checked-button-color: "#009688"
      paper-toggle-button-checked-bar-color: "#99d5cf"
      paper-slider-knob-color: "#66c0b7"
      paper-slider-knob-start-color: "#32ab9f"
      paper-slider-pin-color: "#66c0b7"
      paper-slider-active-color: "#009688"
      paper-slider-secondary-color: "#009688"